name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        python: [3.8, 3.7, 3.6]
        # arch: [x64, x86]
        os: [ubuntu, windows, macos]
        # dotnet: [mono, core, framework]
      fail-fast: false

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          # architecture: ${{ matrix.arch }}

      - name: Build
        run: pip install -e .

      - name: Tests for embedding Python into .NET
        run: dotnet test

      - name: Tests for embedding .NET into Python
        if: always()
        run: pip install pytest && pytest
